#!/bin/bash

echo "Testing OpenCode Sub-Session Navigation Fixes"
echo "============================================"
echo ""
echo "This script will help test the two fixes:"
echo "1. Ctrl+B navigation refresh issue"
echo "2. Sub-session filtering issue"
echo ""
echo "Prerequisites:"
echo "- Make sure you have the backend running: bun run ./src/index.ts serve --port 8812"
echo "- Build the TUI: cd packages/tui && go build -o dgmo cmd/dgmo/main.go"
echo ""
echo "Test 1: Sub-Session Filtering"
echo "-----------------------------"
echo "1. Start dgmo"
echo "2. Create some sub-sessions using: 'Create 3 agents to test navigation'"
echo "3. Press / and type 'sub-session' (or use Ctrl+X U)"
echo "4. EXPECTED: Dialog should show ONLY the 3 sub-sessions you just created"
echo "5. NOT EXPECTED: Should NOT show all sub-sessions from other sessions"
echo ""
echo "Test 2: Ctrl+B Navigation Refresh"
echo "---------------------------------"
echo "1. From the sub-session dialog, press Enter to load a sub-session"
echo "2. Once in the sub-session, press Ctrl+B to go back to parent"
echo "3. EXPECTED: Screen should update immediately showing parent session"
echo "4. NOT EXPECTED: Should NOT need to resize terminal to see the change"
echo ""
echo "Test 3: Combined Test"
echo "--------------------"
echo "1. Navigate to a sub-session (Enter key)"
echo "2. Open /sub-session dialog again"
echo "3. EXPECTED: Should show siblings of current sub-session"
echo "4. Press Ctrl+B to go back"
echo "5. EXPECTED: Immediate refresh to parent session"
echo ""
echo "Debug Logs to Watch:"
echo "- [NAV] prefixed logs show navigation state"
echo "- [SUB-SESSION] prefixed logs show dialog loading"
echo "- Check ~/.local/share/opencode/project/.../log/tui.log for details"
echo ""
echo "Press Enter to continue..."
read

# Optional: Start the TUI
cd /mnt/c/Users/jehma/Desktop/AI/DGMSTT/opencode/packages/tui
./dgmo