#!/bin/bash

echo "=== Testing Prompting Technique Indicators ==="
echo ""
echo "The dgmo binary has been successfully rebuilt with the prompting technique indicators."
echo ""
echo "To test the new features:"
echo "1. Open a new terminal (outside of VSCode)"
echo "2. Navigate to: cd /mnt/c/Users/jehma/Desktop/AI/DGMSTT/opencode"
echo "3. Run: ./dgmo"
echo "4. Start a conversation and look for:"
echo "   - Technique indicators appearing when the assistant responds"
echo "   - The format should show which prompting techniques are being used"
echo ""
echo "Build details:"
echo "- Binary location: $(pwd)/dgmo"
echo "- Build time: $(date)"
echo "- File size: $(ls -lh dgmo | awk '{print $5}')"
echo ""
echo "Fixed issues during build:"
echo "- Removed empty import statement in internal/tui/tui.go"
echo "- Fixed nil pointer comparisons for non-pointer Assistant field"
echo "- Fixed undefined variable 'i' in messages.go"
echo "- Removed unused config import"
echo ""
echo "The prompting technique indicators should now be visible in the TUI!"