#!/bin/bash

echo "Sub-Session Navigation Test Guide"
echo "================================="
echo ""
echo "1. Start the backend server:"
echo "   cd packages/opencode"
echo "   bun run ./src/index.ts serve --port 8812"
echo ""
echo "2. In another terminal, run the TUI:"
echo "   cd packages/tui"
echo "   export DGMO_SERVER=\"http://localhost:8812\""
echo "   export DGMO_APP_INFO='{\"name\":\"dgmstt\",\"version\":\"1.0.0\",\"path\":{\"root\":\"/mnt/c/Users/jehma/Desktop/AI/DGMSTT/opencode\",\"data\":\"/home/jehma/.local/share/opencode/project/mnt-c-Users-jehma-Desktop-AI-DGMSTT-opencode\",\"cwd\":\"/mnt/c/Users/jehma/Desktop/AI/DGMSTT/opencode\"},\"time\":{\"initialized\":0},\"git\":false}'"
echo "   ./dgmo"
echo ""
echo "3. Test Navigation:"
echo "   a. Create sub-sessions: 'Create 3 agents to test navigation'"
echo "   b. Open sub-session dialog: /sub-session"
echo "   c. Press Enter on a sub-session to load it"
echo "   d. Press Ctrl+B to return to parent"
echo "   e. Press Ctrl+B again to go back to sub-session"
echo "   f. In a sub-session, press Ctrl+B then . for next sibling"
echo "   g. In a sub-session, press Ctrl+B then , for previous sibling"
echo ""
echo "Expected Results:"
echo "- Enter key loads sub-session with all messages"
echo "- Ctrl+B navigates back to parent from sub-session"
echo "- Ctrl+B from main session returns to last viewed sub-session"
echo "- Ctrl+B+. and Ctrl+B+, navigate between siblings"
echo "- Toast messages confirm navigation"
echo "- Session title updates in UI"