#!/bin/bash

echo "OpenCode Tasks UI Test Script"
echo "============================="
echo ""
echo "This script demonstrates the new Tasks UI panel in OpenCode TUI."
echo ""
echo "Prerequisites:"
echo "1. Start the OpenCode backend server:"
echo "   cd packages/opencode && bun run ./src/index.ts serve --port 8812"
echo ""
echo "2. In another terminal, run the TUI:"
echo "   cd packages/tui && ./opencode-tui"
echo ""
echo "Testing the Tasks UI:"
echo ""
echo "1. Toggle Tasks Panel:"
echo "   - Press Ctrl+T to show/hide the tasks panel"
echo "   - The panel appears on the right side (30% width)"
echo ""
echo "2. Switch Focus:"
echo "   - Press Tab to switch focus between chat and tasks panel"
echo "   - When tasks panel is focused, it shows a highlighted border"
echo ""
echo "3. Navigate Tasks (when focused):"
echo "   - Use ↑/↓ or j/k to navigate through tasks"
echo "   - Press g to go to the top"
echo "   - Press G to go to the bottom"
echo ""
echo "4. Create Test Tasks:"
echo "   In the chat, type: 'Create 3 agents to write poems about nature'"
echo "   This will create 3 parallel tasks that appear in the panel"
echo ""
echo "5. Visual Features:"
echo "   - Running tasks show animated spinners"
echo "   - Progress bars update in real-time"
echo "   - Completed tasks show green checkmarks"
echo "   - Failed tasks show red X marks"
echo "   - Elapsed time updates every second"
echo ""
echo "6. Task Icons:"
echo "   Different task types show different icons:"
echo "   - 🔍 for search tasks"
echo "   - 📝 for edit/write tasks"
echo "   - 🚀 for build/deploy tasks"
echo "   - 🧪 for test tasks"
echo "   - 🐛 for debug tasks"
echo ""
echo "WebSocket Connection:"
echo "The tasks panel connects to ws://localhost:5747 for real-time updates."
echo "If you see connection errors, ensure the backend server is running."
echo ""
echo "Keyboard Shortcuts Summary:"
echo "- Ctrl+T: Toggle tasks panel"
echo "- Tab: Switch focus between chat and tasks"
echo "- ↑/↓ or j/k: Navigate tasks (when focused)"
echo "- g/G: Go to top/bottom of task list"
echo ""