#!/bin/bash

echo "Testing /continue command session-specific prompt generation fix"
echo "================================================================"
echo ""
echo "This test verifies that each session generates its own unique continuation"
echo "prompt based on the actual work done in that session."
echo ""
echo "Test Steps:"
echo "1. Start the server: cd packages/opencode && bun run dev"
echo "2. Start the TUI: cd packages/tui && ./cmd/dgmo/dgmo"
echo "3. Create Session 1:"
echo "   - Type: 'Help me implement a REST API for user management'"
echo "   - Let the assistant respond"
echo "   - Type: '/continue'"
echo "   - Verify the continuation prompt mentions REST API and user management"
echo ""
echo "4. Create Session 2 (use /new):"
echo "   - Type: 'Debug the WebSocket connection issues in the chat app'"
echo "   - Let the assistant respond"
echo "   - Type: '/continue'"
echo "   - Verify the continuation prompt mentions WebSocket and chat app"
echo "   - Confirm it's different from Session 1's prompt"
echo ""
echo "5. Create Session 3 (use /new):"
echo "   - Type: 'Write unit tests for the payment processing module'"
echo "   - Let the assistant respond"
echo "   - Type: '/continue'"
echo "   - Verify the continuation prompt mentions unit tests and payment"
echo "   - Confirm it's different from previous prompts"
echo ""
echo "Expected Results:"
echo "- Each session should generate a unique continuation prompt"
echo "- Prompts should reflect the actual conversation in that session"
echo "- File paths mentioned in conversation should appear in the prompt"
echo "- No hardcoded 'opencode' or default tasks should appear"
echo ""
echo "Known Issues Fixed:"
echo "- Previously all sessions would generate the same default prompt"
echo "- Now each session analyzes its own messages for context"
echo ""